spring:
  kafka:
    bootstrap-servers: kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: feed_app
    local-datacenter: datacenter1
    schema-action: none

  flyway:
    enabled: true
    url: jdbc:cassandra://localhost:9042/feed_app   # подключаемся к системному keyspace
    user: cassandra
    password: cassandra
    locations: classpath:db/migration
    sql-migration-suffixes: cql

subscription:
  service:
    url: http://localhost:8082